# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [2]:
# Create a NumPy array of shape (5, 5) filled with random integers
import numpy as np
arr = np.random.randint(1,21, size=(5,5))
print(arr)

# Replace all the elements in the third column with 1.
arr[:, 2] = 1
print(f"Modified Array: {arr}")

[[17 12  9 20  5]
 [ 4 14  6 18  2]
 [ 6  2 18  8  9]
 [ 1 10  9  7 19]
 [12  3  2 18  2]]
Modified Array: [[17 12  1 20  5]
 [ 4 14  1 18  2]
 [ 6  2  1  8  9]
 [ 1 10  1  7 19]
 [12  3  1 18  2]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [3]:
arr = np.random.randint(1,17, size=(4,4))
print(arr)

np.fill_diagonal(arr,0)
print("Modified Array: ")
print(arr)

[[16  2  1 11]
 [ 5  5  3  5]
 [11 11  1  4]
 [ 4  3 11  9]]
Modified Array: 
[[ 0  2  1 11]
 [ 5  0  3  5]
 [11 11  0  4]
 [ 4  3 11  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [4]:
## 2.1
arr = np.random.randint(1,36, size=(6,6))
print("Origin Array: ")
print(arr)
print("Sub-Array: ")
print(arr[2:5,1:4])

Origin Array: 
[[26 31  8 13 14 31]
 [10  8 23 30 29 21]
 [10 34 32 20 18  1]
 [11 11 32 33 15 11]
 [ 3 32  4 16  1  9]
 [13  5 22  3 33 31]]
Sub-Array: 
[[34 32 20]
 [11 32 33]
 [32  4 16]]


In [5]:
## 2.2 Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.
arr = np.random.randint(1,21,size=(5,5))
print("Origin Array: ")
print(arr)
# Extract the elements on the border
border_elements = np.concatenate((arr[0, :], arr[-1, :], arr[1:-1, 0], arr[1:-1, -1]))
print("Border elements:")
print(border_elements)

Origin Array: 
[[ 3 20 19  4  6]
 [18 18 20  3  8]
 [ 9 19  3 18  6]
 [17 18  7 16 14]
 [13 20  7 20 17]]
Border elements:
[ 3 20 19  4  6 13 20  7 20 17 18  9 17  8  6 14]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [6]:
## 3.1 Create two NumPy arrays of shape (3,4) filled with random integers, Perform element-wise addition, subtraction, multiplication, and division
arr1 = np.random.randint(1,21, size=(3,4))
print("Array 1 = ")
print(arr1)
arr2 = np.random.randint(1,21, size=(3,4))
print("Array 2 = ")
print(arr2)

print("Element wise Addition: ")
addition  = arr1 + arr2
print(addition)

print("Element wise Substraction: ")
addition  = arr1 - arr2
print(addition)

print("Element wise Multiplication: ")
addition  = arr1 * arr2
print(addition)

print("Element wise Divition: ")
addition  = arr1 / arr2
print(addition)



Array 1 = 
[[10 15 10  9]
 [ 4  4 17 11]
 [14  4  7  5]]
Array 2 = 
[[12 11  5 15]
 [ 9 13 12  4]
 [15 19 15  7]]
Element wise Addition: 
[[22 26 15 24]
 [13 17 29 15]
 [29 23 22 12]]
Element wise Substraction: 
[[ -2   4   5  -6]
 [ -5  -9   5   7]
 [ -1 -15  -8  -2]]
Element wise Multiplication: 
[[120 165  50 135]
 [ 36  52 204  44]
 [210  76 105  35]]
Element wise Divition: 
[[0.83333333 1.36363636 2.         0.6       ]
 [0.44444444 0.30769231 1.41666667 2.75      ]
 [0.93333333 0.21052632 0.46666667 0.71428571]]


In [7]:
## 3.2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.
arr = np.arange(1,17).reshape(4,4)
print("Origin Array: ")
print(arr)

row_wise_sum = np.sum(arr,axis=1)
print(f"Row wise addition: {row_wise_sum}")

column_wise_sum = np.sum(arr, axis=0)
print(f"Column wise addition: {column_wise_sum}")

Origin Array: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row wise addition: [10 26 42 58]
Column wise addition: [28 32 36 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [8]:
## 4.1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
arr = np.random.randint(1,21, size=(5,5))
print("Origin Array: ")
print(arr)

mean = np.mean(arr)
print(f"Mean = {mean}")

median = np.median(arr)
print(f"Median = {median}")

std = np.std(arr)
print(f"Standard Deviation = {std :.2f}")

varience = np.var(arr)
print(f"Varience = {varience :.2f}")

Origin Array: 
[[17  4  4  5  6]
 [ 9  1 19  8 10]
 [13 11  1 12 16]
 [13  9 11 19  4]
 [ 2 20  4 13  5]]
Mean = 9.44
Median = 9.0
Standard Deviation = 5.71
Varience = 32.57


In [9]:
## 4.2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).
arr = np.arange(1,10).reshape(3,3)
print("Original Array:")
print(arr)

mean = np.mean(arr)
std = np.std(arr)
normalized_array = (arr - mean) /std
print("Normalized Array: ")
print(normalized_array)


Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized Array: 
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [12]:
## 5.1
arr = np.random.randint(1,21,size=(3,3))
row_arr = np.random.randint(1,21,size=(3,))
print("Array: ")
print(arr)
print("1D Array: ")
print(row_arr)

result = arr + row_arr
print("Array using Brodcating: ")
print(result)


Array: 
[[ 2 11  8]
 [18 19 16]
 [16 16  1]]
1D Array: 
[18  2 20]
Array using Brodcating: 
[[20 13 28]
 [36 21 36]
 [34 18 21]]


In [16]:
# 5.2 Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.
arr = np.random.randint(1,21,size=(4,4))
print("Original Array: ")
print(arr)

row_arr = np.random.randint(1,11, size=(4))
print(row_arr)

result = arr - row_arr
print(result)

Original Array: 
[[13  6 11  1]
 [ 4 19 18 19]
 [14 13  2  6]
 [ 7  3 19 10]]
[9 5 4 1]
[[ 4  1  7  0]
 [-5 14 14 18]
 [ 5  8 -2  5]
 [-2 -2 15  9]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.