# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [1]:
# Create a NumPy array of shape (5, 5) filled with random integers
import numpy as np
arr = np.random.randint(1,21, size=(5,5))
print(arr)

# Replace all the elements in the third column with 1.
arr[:, 2] = 1
print(f"Modified Array: {arr}")

[[ 3 15 16  5  6]
 [ 4  5  3 19  5]
 [20  8  8  4 19]
 [20  8  1 17  8]
 [12 10 11 15  4]]
Modified Array: [[ 3 15  1  5  6]
 [ 4  5  1 19  5]
 [20  8  1  4 19]
 [20  8  1 17  8]
 [12 10  1 15  4]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [2]:
arr = np.random.randint(1,17, size=(4,4))
print(arr)

np.fill_diagonal(arr,0)
print("Modified Array: ")
print(arr)

[[ 7 13 11  8]
 [ 1  5 15 15]
 [ 6 13  4  7]
 [ 5 12  1  7]]
Modified Array: 
[[ 0 13 11  8]
 [ 1  0 15 15]
 [ 6 13  0  7]
 [ 5 12  1  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [3]:
## 2.1
arr = np.random.randint(1,36, size=(6,6))
print("Origin Array: ")
print(arr)
print("Sub-Array: ")
print(arr[2:5,1:4])

Origin Array: 
[[16 34 22 25 28  1]
 [21 26 16 11  2  8]
 [14  1 32 33  4 26]
 [17 16  5 11 30 19]
 [13 30 23 15  5 35]
 [30 31 15  7 35 35]]
Sub-Array: 
[[ 1 32 33]
 [16  5 11]
 [30 23 15]]


In [4]:
## 2.2 Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.
arr = np.random.randint(1,21,size=(5,5))
print("Origin Array: ")
print(arr)
# Extract the elements on the border
border_elements = np.concatenate((arr[0, :], arr[-1, :], arr[1:-1, 0], arr[1:-1, -1]))
print("Border elements:")
print(border_elements)

Origin Array: 
[[ 7  5 20 14 18]
 [19 11  5 14 16]
 [ 9  4 13 15 14]
 [ 8  5  9 11 17]
 [19 13  1 13 19]]
Border elements:
[ 7  5 20 14 18 19 13  1 13 19 19  9  8 16 14 17]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [5]:
## 3.1 Create two NumPy arrays of shape (3,4) filled with random integers, Perform element-wise addition, subtraction, multiplication, and division
arr1 = np.random.randint(1,21, size=(3,4))
print("Array 1 = ")
print(arr1)
arr2 = np.random.randint(1,21, size=(3,4))
print("Array 2 = ")
print(arr2)

print("Element wise Addition: ")
addition  = arr1 + arr2
print(addition)

print("Element wise Substraction: ")
addition  = arr1 - arr2
print(addition)

print("Element wise Multiplication: ")
addition  = arr1 * arr2
print(addition)

print("Element wise Divition: ")
addition  = arr1 / arr2
print(addition)



Array 1 = 
[[17 11  8  1]
 [15  6 10  8]
 [ 3  1  6 19]]
Array 2 = 
[[ 8  2  9 13]
 [ 8 15  1 18]
 [11 13  7 12]]
Element wise Addition: 
[[25 13 17 14]
 [23 21 11 26]
 [14 14 13 31]]
Element wise Substraction: 
[[  9   9  -1 -12]
 [  7  -9   9 -10]
 [ -8 -12  -1   7]]
Element wise Multiplication: 
[[136  22  72  13]
 [120  90  10 144]
 [ 33  13  42 228]]
Element wise Divition: 
[[ 2.125       5.5         0.88888889  0.07692308]
 [ 1.875       0.4        10.          0.44444444]
 [ 0.27272727  0.07692308  0.85714286  1.58333333]]


In [6]:
## 3.2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.
arr = np.arange(1,17).reshape(4,4)
print("Origin Array: ")
print(arr)

row_wise_sum = np.sum(arr,axis=1)
print(f"Row wise addition: {row_wise_sum}")

column_wise_sum = np.sum(arr, axis=0)
print(f"Column wise addition: {column_wise_sum}")

Origin Array: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row wise addition: [10 26 42 58]
Column wise addition: [28 32 36 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [7]:
## 4.1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
arr = np.random.randint(1,21, size=(5,5))
print("Origin Array: ")
print(arr)

mean = np.mean(arr)
print(f"Mean = {mean}")

median = np.median(arr)
print(f"Median = {median}")

std = np.std(arr)
print(f"Standard Deviation = {std :.2f}")

varience = np.var(arr)
print(f"Varience = {varience :.2f}")

Origin Array: 
[[13  4  2 20 11]
 [ 2 20  5  8 16]
 [11  7 16  8 20]
 [ 6  1 16 16  5]
 [ 1  6 15 15  9]]
Mean = 10.12
Median = 9.0
Standard Deviation = 6.10
Varience = 37.23


In [8]:
## 4.2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).
arr = np.arange(1,10).reshape(3,3)
print("Original Array:")
print(arr)

mean = np.mean(arr)
std = np.std(arr)
normalized_array = (arr - mean) /std
print("Normalized Array: ")
print(normalized_array)


Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized Array: 
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [9]:
## 5.1
arr = np.random.randint(1,21,size=(3,3))
row_arr = np.random.randint(1,21,size=(3,))
print("Array: ")
print(arr)
print("1D Array: ")
print(row_arr)

result = arr + row_arr
print("Array using Brodcating: ")
print(result)


Array: 
[[20  4 15]
 [10 16 18]
 [ 1  1 20]]
1D Array: 
[20 13  8]
Array using Brodcating: 
[[40 17 23]
 [30 29 26]
 [21 14 28]]


In [10]:
# 5.2 Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.
arr = np.random.randint(1,21,size=(4,4))
print("Original Array: ")
print(arr)

row_arr = np.random.randint(1,11, size=(4))
print(row_arr)

result = arr - row_arr
print(result)

Original Array: 
[[20 15 18 17]
 [17  9  9 19]
 [ 4 10  8 11]
 [19 14  9  3]]
[10  7  4 10]
[[10  8 14  7]
 [ 7  2  5  9]
 [-6  3  4  1]
 [ 9  7  5 -7]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [11]:
## 6.1 
matrix = np.random.randint(1,21,size=(3,3))
print("Matrix: ")
print(matrix)

determinant = np.linalg.det(matrix)
print(f"determinant: {determinant}")

inverse = np.linalg.inv(matrix)
print(inverse)

eigenvalues = np.linalg.eigvals(matrix)
print(eigenvalues)

Matrix: 
[[14 12 15]
 [12 18  5]
 [19  6 11]]
determinant: -2142.0
[[-0.07843137  0.01960784  0.09803922]
 [ 0.01727358  0.0611578  -0.05135387]
 [ 0.12605042 -0.06722689 -0.05042017]]
[37.63489171 -5.32440321 10.6895115 ]


In [14]:
## 6.2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.
arr1 = np.random.randint(1,11,size=(2,3))
arr2 = np.random.randint(1,11,size=(3,2))

print("Array 1: ")
print(arr1)

print("Array 2: ")
print(arr2)

print("Matrix Multiplication using `dot()` function")
matrix_multi = np.dot(arr1, arr2)
print(matrix_multi)

Array 1: 
[[ 4  1 10]
 [ 5  8  4]]
Array 2: 
[[5 8]
 [9 4]
 [5 6]]
Matrix Multiplication using `dot()` function
[[ 79  96]
 [117  96]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [23]:
## 7.1 

arr = np.arange(1, 10).reshape((3, 3))
print("Original array:")
print(arr)

arr1 = arr.reshape(1,9)
print("Array with size (1,9): ")
print(arr1)

print("Array with size (9,1)")
arr2 = arr.reshape((1,9))
print(arr2)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Array with size (1,9): 
[[1 2 3 4 5 6 7 8 9]]
Array with size (9,1)
[[1 2 3 4 5 6 7 8 9]]


In [ ]:
# 7.2 Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).



### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.